# Generated by Django 3.0.7 on 2020-07-06 08:22

from django.db import migrations, models
import interviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='image',
            field=models.ImageField(blank=True, upload_to=interviews.models.articles_image_path),
        ),
    ]
